Friend Module Constants
    Friend Const AbandonGameTitle = "[red]Are you sure you want to abandon game?[/]"
    Friend Const AbandonText = "Abandon Game"
    Friend Const ConfirmQuitTitle = "[red]Are you sure you want to quit?[/]"
    Friend Const ContinueText = "Continue"
    Friend Const EmbarkText = "Embark!"
    Friend Const GameTitle = "A Game about Color Being the Most Important Mechanic"
    Friend Const MainMenuTitle = "[olive]Main Menu:[/]"
    Friend Const MainMenuText = "Main Menu"
    Friend Const NoText = "No"
    Friend Const NowWhatTitle = "[olive]Now What?[/]"
    Friend Const OkText = "Ok"
    Friend Const QuitText = "Quit"
    Friend Const YesText = "Yes"
End Module
