Friend Module Constants
    Friend Const AbandonGameTitle = "[red]Are you sure you want to abandon game?[/]"
    Friend Const AbandonText = "Abandon Game"
    Friend Const ChooseEnemyTitle = "[olive]Choose Enemy:[/]"
    Friend Const ConfirmQuitTitle = "[red]Are you sure you want to quit?[/]"
    Friend Const ContinueText = "Continue"
    Friend Const EmbarkText = "Embark!"
    Friend Const FightText = "Fight!"
    Friend Const GameTitle = "A Game about Color Being the Most Important Mechanic"
    Friend Const InteractText = "Interact..."
    Friend Const InventoryText = "Inventory"
    Friend Const LoadText = "Load..."
    Friend Const MainMenuTitle = "[olive]Main Menu:[/]"
    Friend Const MainMenuText = "Main Menu"
    Friend Const MoveTitle = "Move Title"
    Friend Const MoveText = "Move"
    Friend Const NeverMindText = "Never Mind"
    Friend Const NoText = "No"
    Friend Const NowWhatTitle = "[olive]Now What?[/]"
    Friend Const OkText = "Ok"
    Friend Const QuitText = "Quit"
    Friend Const SaveText = "Save..."
    Friend Const YesText = "Yes"
End Module
